// Mock data for TikTok Ranking products
export const mockProducts = Array(10).fill(null).map((_, index) => ({
    id: index + 1,
    rank: index + 1,
    productName: '商品名商品名商品名商品名商品名商品名',
    price: '¥1,045',
    brand: 'KYOGOKU',
    category: 'カテゴリー',
    commission: 'XX%',
    salesComparison: 'XXX%',
    revenue: '¥XXXX.X万',
    cumulativeSales: 'XXXXX',
    cumulativeRevenue: '¥XXXX.X万',
    storeInfo: '店舗販売数：XXXX',
    isFavorite: false,
    image: '/api/placeholder/72/72',
    storeImage: '/api/placeholder/64/64'
}));

// Alternative mock data with more realistic values
export const mockProductsRealistic = [
    {
        id: 1,
        rank: 1,
        productName: 'ヘアケアシャンプー プレミアム',
        price: '¥2,980',
        brand: 'KYOGOKU',
        category: 'ヘアケア',
        commission: '15%',
        salesComparison: '+120%',
        revenue: '¥850.5万',
        cumulativeSales: '12,450',
        cumulativeRevenue: '¥3,712.1万',
        storeInfo: '店舗販売数：8,920',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 2,
        rank: 2,
        productName: 'スキンケアセット 美白効果',
        price: '¥4,500',
        brand: 'BEAUTY PRO',
        category: 'スキンケア',
        commission: '20%',
        salesComparison: '+95%',
        revenue: '¥720.3万',
        cumulativeSales: '9,850',
        cumulativeRevenue: '¥2,891.7万',
        storeInfo: '店舗販売数：6,430',
        isFavorite: true,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 3,
        rank: 3,
        productName: 'メイクアップ リップセット',
        price: '¥1,890',
        brand: 'GLAMOUR',
        category: 'メイクアップ',
        commission: '12%',
        salesComparison: '+85%',
        revenue: '¥680.2万',
        cumulativeSales: '15,200',
        cumulativeRevenue: '¥2,872.8万',
        storeInfo: '店舗販売数：11,200',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 4,
        rank: 4,
        productName: 'フィットネスウェア セット',
        price: '¥3,200',
        brand: 'SPORT LIFE',
        category: 'フィットネス',
        commission: '18%',
        salesComparison: '+75%',
        revenue: '¥512.8万',
        cumulativeSales: '8,900',
        cumulativeRevenue: '¥2,284.8万',
        storeInfo: '店舗販売数：5,600',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 5,
        rank: 5,
        productName: 'サプリメント ビタミンC',
        price: '¥1,200',
        brand: 'HEALTH PLUS',
        category: 'サプリメント',
        commission: '25%',
        salesComparison: '+65%',
        revenue: '¥456.0万',
        cumulativeSales: '22,100',
        cumulativeRevenue: '¥2,652.0万',
        storeInfo: '店舗販売数：18,900',
        isFavorite: true,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 6,
        rank: 6,
        productName: 'アクセサリー ネックレス',
        price: '¥5,800',
        brand: 'JEWEL STAR',
        category: 'アクセサリー',
        commission: '30%',
        salesComparison: '+55%',
        revenue: '¥398.6万',
        cumulativeSales: '4,570',
        cumulativeRevenue: '¥2,650.6万',
        storeInfo: '店舗販売数：3,200',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 7,
        rank: 7,
        productName: 'ホームケア 掃除用品セット',
        price: '¥2,100',
        brand: 'CLEAN HOME',
        category: 'ホームケア',
        commission: '14%',
        salesComparison: '+45%',
        revenue: '¥357.0万',
        cumulativeSales: '11,900',
        cumulativeRevenue: '¥2,499.0万',
        storeInfo: '店舗販売数：9,800',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 8,
        rank: 8,
        productName: 'キッチン用品 調理器具',
        price: '¥3,800',
        brand: 'COOK MASTER',
        category: 'キッチン用品',
        commission: '16%',
        salesComparison: '+35%',
        revenue: '¥323.8万',
        cumulativeSales: '6,750',
        cumulativeRevenue: '¥2,565.0万',
        storeInfo: '店舗販売数：4,900',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 9,
        rank: 9,
        productName: 'ペット用品 おもちゃセット',
        price: '¥1,500',
        brand: 'PET JOY',
        category: 'ペット用品',
        commission: '22%',
        salesComparison: '+25%',
        revenue: '¥285.0万',
        cumulativeSales: '14,200',
        cumulativeRevenue: '¥2,130.0万',
        storeInfo: '店舗販売数：12,100',
        isFavorite: true,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    },
    {
        id: 10,
        rank: 10,
        productName: 'ファッション バッグ',
        price: '¥7,200',
        brand: 'FASHION STYLE',
        category: 'ファッション',
        commission: '28%',
        salesComparison: '+15%',
        revenue: '¥259.2万',
        cumulativeSales: '2,890',
        cumulativeRevenue: '¥2,080.8万',
        storeInfo: '店舗販売数：2,100',
        isFavorite: false,
        image: '/api/placeholder/72/72',
        storeImage: '/api/placeholder/64/64'
    }
];

// Categories for filtering
export const categories = [
    'ALL',
    'ヘアケア',
    'スキンケア',
    'メイクアップ',
    'フィットネス',
    'サプリメント',
    'アクセサリー',
    'ホームケア',
    'キッチン用品',
    'ペット用品',
    'ファッション',
    'ヘアケア',
    'スキンケア',
    'メイクアップ',

];

// Period options
export const periodOptions = [
    '日間ランキング',
    '週間ランキング',
    '月間ランキング'
];
